//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Książka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Książka()
        {
            this.Autorzy = new HashSet<Autorzy>();
            this.Kategoria_Książka = new HashSet<Kategoria_Książka>();
            this.Kopia = new HashSet<Kopia>();
        }
    
        public int ID { get; set; }
        public string Tytuł { get; set; }
        public string ISBN { get; set; }
        public System.DateTime Rok_wydania { get; set; }
        public int ID_Wydawca { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Autorzy> Autorzy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kategoria_Książka> Kategoria_Książka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kopia> Kopia { get; set; }
        public virtual Wydawca Wydawca { get; set; }
    }
}
