//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oddanie
    {
        public System.DateTime Data_oddania { get; set; }
        public Nullable<int> Stan_przed_oddaniem { get; set; }
        public Nullable<int> Stan_po_oddaniu { get; set; }
        public int ID_wypożyczenie { get; set; }
    
        public virtual Stan_Książki Stan_Książki { get; set; }
        public virtual Stan_Książki Stan_Książki1 { get; set; }
        public virtual Wypożyczenie Wypożyczenie { get; set; }
    }
}
