//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wypożyczenie
    {
        public int ID { get; set; }
        public int ID_Kopia { get; set; }
        public System.DateTime Data_wypożyczenia { get; set; }
        public int ID_Karta { get; set; }
        public System.DateTime Oczekiwana_data_zwrotu { get; set; }
    
        public virtual Karta Karta { get; set; }
        public virtual Kopia Kopia { get; set; }
        public virtual Oddanie Oddanie { get; set; }
    }
}
